name: Format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    name: Format code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install SwiftFormat
        uses: Cyberbeni/install-swift-tool@v2
        with:
          url: https://github.com/nicklockwood/SwiftFormat

      - name: Format Go code
        run: go fmt ./...

      - name: Format Swift code
        run: swiftformat --verbose .

      - name: Verify formatted code is unchanged
        run: git diff --exit-code HEAD -w -G'(^[^# /])|(^#\w)|(^\s+[^#/])' # Ignore whitespace and comments
