name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  swift:
    name: Test Swift
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # - name: Set Xcode version
      #   run: sudo xcode-select -switch "/Applications/Xcode_13.app" # Comment this out when Xcode 13 is default on GHA runners

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1

      - name: Build
        run: make build

      - name: Test Go
        run: go test -v ./...

      - name: Test Swift
        run: swift test

      - name: Verify repo is unchanged
        run: git diff --exit-code HEAD -w -G'(^[^# /])|(^#\w)|(^\s+[^#/])' # Ignore whitespace and comments
