name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  swift:
    name: Test Swift
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1

      - name: Test
        run: make test
